version: "3"
services:
  api:
    build:
      context: ./application
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./application:/app
    depends_on:
      - mongodb
    networks: 
      - vidly-network
    # this is for react projects that may have some issues: start
    stdin_open: true 
    tty: true 
    # this is for react projects that may have some issues: end

  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb-vol:/var/lib/mongodb
    networks: 
      - vidly-network

  # this sets up mongodb to run rs.initiate() for transactions and replication to work 
  mongosetup:
    build:
      context: ./database
      dockerfile: Dockerfile-setup.dev
    depends_on:
      - mongodb
    restart: "no"
    networks: 
      - vidly-network

networks: 
  vidly-network:
    driver: bridge

volumes: 
  mongodb-vol:
    driver: local