version: "3"
services:
  vidly-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # this is for react projects that may have some issues: start
    stdin_open: true 
    tty: true 
    # this is for react projects that may have some issues: end
    ports:
      - "4000:80"
    volumes:
      - .:/app      
    environment: 
      - TEST_VARIABLE=testvar_production
    env_file: 
      - ./.env.dev